#!/usr/bin/env python3
#
# System imports
#
#=======================================================================
#
#
#  Python Makefile-thing for COMMAS
#
#
#=======================================================================

import sys, os
#import platform

RANLIB = "'ranlib'"
AR     = "'ar -rc'"
MAKE   = 'make -j3 -f ../src/Makefile' # --debug'
ELECON = "1"
#MAKE   = 'make -f Makefile.tmp' # --debug'

# define less-used options as null
OPT_BUOY = "''"
OPT_SLV  = "''"

#=======================================================================
#
#
# Function to do the makefile calls

def makeit(current_dir,makefile_dir,target,compile_options,mpisuf):

    print("Change directory to " + makefile_dir)

    if os.path.exists(makefile_dir):
        os.chdir(makefile_dir)
    else:
        print("ERROR!!! ")
        print("ERROR!!! Build directory does not exist, so will create it: " + makefile_dir)
        print("ERROR!!! ")
        os.system('mkdir ' + makefile_dir)
        os.chdir(makefile_dir)

    print()
    print("Making " + target)

    MAKE_CMD = MAKE + " " + target + " " + compile_options + ' ELECON=' + ELECON

    if os.system(MAKE_CMD) != 0:
        print()
        print("ERROR!!! ")
        print("ERROR!!!  Failed to compile " + target)
        print("ERROR!!! ")
        print()
        os.chdir(current_dir)
        return 0

    print("Finished compiling " + target)

    LINK_CMD = 'ln -s ' + makefile_dir + '/' + target + ' ' + current_dir + '/' + target + mpisuf

    if os.system(LINK_CMD) != 0:
        print()
        print("ERROR!!! ")
        print("ERROR!!!  Failed to link " + target)
        print("ERROR!!! ")
        print()
        os.chdir(current_dir)
        return 0

    print("Linking " + target + " to main directory")

    COPY_CMD = 'cp -f ' + target + ' ' +  '../exedir/' + target + mpisuf

    print("Copying " + target + " to exe directory")
#        print "copy_cmd = " + COPY_CMD

    if os.path.exists('../exedir'):

            if os.system(COPY_CMD) != 0:
                    print()
                    print("ERROR!!! ")
                    print("ERROR!!!  Failed to copy" + target)
                    print("ERROR!!! ")
                    print()
                    os.chdir(current_dir)
                    return 0
    else:
            print("exedir does not exist -- create link to copy executables if desired")

    print()
    os.chdir(current_dir)

    return 1
#
#
#=======================================================================
# main script

# Figure out which machine we are on

#machine = platform.machine()  # i386, ppc, etc.
#system  = platform.system()   # Darwin, Linux,

un = os.uname()
print(os.uname())
machine = un[4] # platform.machine()  # i386, ppc, etc.
system  = un[0] # platform.system()   # Darwin, Linux,
host    = un[1]

compiler = ""
mpi    = 'yes'

mpisuf = ''
if mpi == 'yes':
    mpisuf = '_mpi'

print()
print("Compiler python script for COMMAS")
print()
print("Machine is ", machine)
print("System is  ", system)
print()

#
# Some macro descriptions:
#
# MOPT4 -> Compile optimization options for ZIEG microphysics scheme
# MOPT5 -> Compile optimization options for ICE10 microphysics scheme
#
#-----------------------------------------------------------------------
#
# Mac Intel ifort Compiler definitions

if machine == 'x86_64' and system == 'Darwin' and mpi == 'yes' and compiler != "g95" and compiler != 'xlf':

#	F90        = "'mpif90'"
#	F77        = "'mpif77'"
#	FPP        = "'mpif90'"
	F90        = "'mpif90 -traceback'"
	F77        = "'mpif77 -traceback'"
	FPP        = "'mpif90 -traceback'"
#	F90        = "'mpif90 -gen-interfaces -warn interfaces -fp-stack-check -g -traceback'"
#	F77        = "'mpif77 -gen-interfaces -warn interfaces -fp-stack-check -g -traceback'"
#	FPP        = "'mpif90 -gen-interfaces -warn interfaces -fp-stack-check -g -traceback'"
	NCARGF     = "'ncargf90'"
	FIXED      = "'-extend_source'"
	FREE       = "'-free'"
	SMP        = "''"
	IPO        = "''" # "'-ipo'"
	OPT_F90    = "'-O2  -fp-model precise -zero -ftz -align all'"        # do not use -O3 on Itanium: it causes problems somewhere
	OPT_ADV    = "'-O3'"
	OPT_F77    = "'-O2 -fp-model precise -zero -ftz -align all'"
	OPT_F77    = "'-O2 -zero -ftz -align all'"
#	OPT_F90    = "'-O2 -g -C -fpe0 -fp-model precise -zero -ftz -align all'"        # do not use -O3 on Itanium: it causes problems somewhere
#	OPT_F90    = "'-O0 -g -fpe0 -C -ftrapuv -traceback -fp-model precise'"
#	OPT_F90    = "'-O2 -g  -C  -traceback -fp-model precise'"
#	OPT_F77    = "'-O0 -g  -C -ftrapuv -fpe0 -traceback -fp-model precise'"
#	OPT_F77    = "'-O0 -g  -fpe0 -ftrapuv -zero -C -align all -ftz -fp-model precise'"
#	OPT_ADV    = "''"
	OPT_SLV    = "'-O2'"            # special options for solver
	OPT_SLV    = "''"            # special options for solver
	GRDOPT     = "''"                                                      # special options for grid_module
#	MOPT4      = "'-O1  -zero -save -ftz -std -gen_interfaces'"
	MOPT4      = "'-O2 -fp-model precise  -zero -save -ftz'"
#	MOPT4      = "'-O2 -fp-model precise  -ftz'"
#	MOPT4      = "'-O2 -ftz -zero -save'"
#	MOPT4      = "'-O0 -C -g -fpe0 -ftrapuv -traceback -fp-model precise   -zero -save -ftz'"
#	MOPT4      = "'-O0 -C -g -fpe0 -ftrapuv -traceback -fp-model precise   '"
#	FPPDEF     = "''"
	MOPT5      = "'-O1  -zero -save -ftz -std -gen_interfaces'"
	FPPDEF     = "''"
	SOROPT     = "'-O3 -ftz -align all'"
#	SOROPT     = "'-O0 -g -C -ftz -align all'"
	PAR        = "''"
#	AR         = "'sync; libtool -static -o'"
	LDR        = "'mpif90 -traceback  -Wl,-w'" # added Wl,-w to suppress linker warnings about versions
	LOPT       = "' -Wl,-w -i_dynamic -openmp'"
	CC         = "'mpicc'"
#	CFLAGS     = "'-c -O -DLITTLE -DUNDERSCORE'"
	CFLAGS     = "'-c -m64 -O -DLITTLE -DUNDERSCORE -DV5D64'"
# uncomment next lines to compile with netCDF4
	DFLAGS     = "'-DNC4 -DMPI -DV5D64 -DBOXMG -DUSEWRF -DUSE_PNETCDF'"
#	DFLAGS     = "'-DNC4 -DMPI -DV5D64 -DUSEWRF'"
#	DFLAGS     = "'-DNC4 -DMPI -DV5D64'"
	NETCDF_LIB = "' -L/Users/Shared/opt/local/mpich332/netcdf474p/lib -lnetcdff -lnetcdf -lhdf5_fortran -lhdf5hl_fortran -lhdf5_hl -lhdf5 -lz -lpnetcdf -L/Users/mansell/src/boxmg-mpi-single/lib_mpich -lboxmg_opt_sgl -lboxmg-extras_opt_sgl '" # -L/opt/local/szip64/lib -lsz'" # -lSystemStubs'"
	NETCDF_INC = "'-I/Users/Shared/opt/local/mpich332/netcdf474p/include -I/Users/mansell/src/boxmg-mpi-single/include -I/Users/mansell/src/boxmg-mpi-single/extras/msg/include'"
	NETCDF_LIB = "' -L/Users/Shared/opt/local/mpich332/netcdf480par/lib -lnetcdff -lnetcdf -lhdf5_fortran -lhdf5hl_fortran -lhdf5_hl -lhdf5 -lz -lpnetcdf -L/Users/mansell/src/boxmg-mpi-single/lib_mpich -lboxmg_opt_sgl -lboxmg-extras_opt_sgl '" # -L/opt/local/szip64/lib -lsz'" # -lSystemStubs'"
	NETCDF_INC = "'-I/Users/Shared/opt/local/mpich332/netcdf480par/include -I/Users/mansell/src/boxmg-mpi-single/include -I/Users/mansell/src/boxmg-mpi-single/extras/msg/include'"
	LIB        = "''"


if machine == 'x86_64' and system == 'Darwin' and mpi == 'yes' and compiler == "gfortran":
	F90        = "'mpif90'"
	F77        = "'mpif77'"
	FPP        = "'mpif90'"
	NCARGF     = "'ncargf90'"
	FIXED      = "'-ffixed-form -ffixed-line-length-256'"
	FREE       = "'-ffree-form -ffree-line-length-256'"
	SMP        = "''"
	IPO        = "''" # "'-ipo'"
	OPT_F90    = "'-O3 -Wno-error'"        # do not use -O3 on Itanium: it causes problems somewhere
	OPT_ADV    = "'-O3 -Wno-error'"
	OPT_F77    = "'-O2 -Wno-error'"
	OPT_F77    = "'-O2 -Wno-error'"
#	OPT_F90    = "'-O0 -g -fpe0 -C -ftrapuv -traceback'"
#	OPT_F90    = "'-O0 -g  -C -fpe0 -traceback'"
#	OPT_F77    = "'-O0 -g  -C -ftrapuv -fpe0 -traceback'"
#	OPT_F77    = "'-O0 -g  -fpe0 -ftrapuv -zero -C -align all -ftz'"
#	OPT_ADV    = "''"
#	OPT_BUOY   = "'-O0'"
	OPT_SLV    = "'-O2'"            # special options for solver
	OPT_SLV    = "''"            # special options for solver
	GRDOPT     = "''"                                                      # special options for grid_module
#	MOPT4      = "'-O1  -zero -save -ftz -std -gen_interfaces'"
#	MOPT4      = "'-O2 -fp-model precise  -zero -save -ftz'"
	MOPT4      = "'-O2'"
#	MOPT4      = "'-O0 -C -g -fpe0 -ftrapuv -traceback -fp-model precise   -zero -save -ftz'"
#	FPPDEF     = "''"
	MOPT5      = "'-O1'"
	FPPDEF     = "''"
	SOROPT     = "'-O3'"
#	SOROPT     = "'-O0 -g -C -ftz -align all'"
	PAR        = "''"
#	AR         = "'sync; libtool -static -o'"
	LDR        = "'mpif90 -fbacktrace'"
	LOPT       = "'-openmp'"
	CC         = "'mpicc'"
#	CFLAGS     = "'-c -O -DLITTLE -DUNDERSCORE'"
	CFLAGS     = "'-c -m64 -O -DLITTLE -DUNDERSCORE -DV5D64'"
#	DFLAGS     = "'-DMPI'"
# uncomment next lines to compile with netCDF4
#	DFLAGS     = "'-DNC4 -DMPI -DV5D64 -DBOXMG -DUSEWRF -DUSE_PNETCDF'"
	DFLAGS     = "'-DNC4 -DMPI -DV5D64 -DUSEWRF'"
#	DFLAGS     = "'-DNC4 -DMPI -DV5D64'"
	NETCDF_LIB = "'-L${NETCDFC_DIR}/lib -lnetcdf -L${NETCDF4_DIR}/lib -lnetcdff -L${HDF5_DIR}/lib -lhdf5_hl -lhdf5 -lz'"
	NETCDF_INC = "'-I${NETCDF4_DIR}/include -I${NETCDF4_DIR}/include -I${HDF5_DIR}/include'"
#	NETCDF_INC = "'-I/Users/Shared/opt/local/netcdf431par/include -I/Users/mansell/src/boxmg-mpi-single/include -I/Users/mansell/src/boxmg-mpi-single/extras/msg/include'"
#	NETCDF_LIB = "' -L/opt/local/netcdf4311/lib -lnetcdff -lnetcdf -lpnetcdf -lhdf5_fortran -lhdf5hl_fortran -lhdf5_hl -lhdf5 -lz -L/Users/mansell/src/boxmg-mpi-single/lib -lboxmg_opt_sgl -lboxmg-extras_opt_sgl'" # -L/opt/local/szip64/lib -lsz'" # -lSystemStubs'"
#	NETCDF_INC = "'-I/opt/local/netcdf4311/include -I/Users/mansell/src/boxmg-mpi-single/include -I/Users/mansell/src/boxmg-mpi-single/extras/msg/include'"
	LIB        = "''"

if machine == 'arm64' and system == 'Darwin' and mpi == 'yes':
	F90        = "'mpif90 -fbacktrace'"
	F77        = "'mpif77 -fbacktrace'"
	FPP        = "'mpif90 -fbacktrace'"
	NCARGF     = "'ncargf90'"
	FIXED      = "'-ffixed-form -ffixed-line-length-256  -fallow-argument-mismatch'"
	FREE       = "'-ffree-form -ffree-line-length-256  -fallow-argument-mismatch'"
	SMP        = "''"
	IPO        = "''" # "'-ipo'"
	OPT_F90    = "'-O3 -Wno-error'"  
	OPT_ADV    = "'-O2 -Wno-error'"
#	OPT_ADV    = "'-O0 -g -ffpe-trap=invalid,zero,overflow -fcheck=all'"
	OPT_F77    = "'-O2 -g -Wno-error'"
#	OPT_F77    = "'-O0 -g -ffpe-trap=invalid,zero,overflow -fcheck=all'"
#	OPT_F90    = "'-O0 -g -fcheck=all'"
#	OPT_F90    = "'-O2  '"
#	OPT_F77    = "'-O0 -g -fcheck=all'"
#	OPT_F90    = "'-O0 -g -ffpe-trap=invalid,zero,overflow -fcheck=all'"
#	OPT_F90    = "'-O2 -g -fcheck=bounds'"
#	OPT_F90    = "'-O2 -g -finit-integer=5000000 -finit-real=inf'"
#	OPT_F90    = "'-O2 -g -Wuninitialized'"
#	OPT_F90    = "'-O2 -g -fcheck=bounds -finit-real=nan'"
#	OPT_F90    = "'-O2 -g -fcheck=bounds -finit-real=snan -ffpe-trap=invalid,zero,overflow'"
#	OPT_ADV    = "''"
#	OPT_BUOY   = "'-O0'"
	OPT_SLV    = "'-O2'"            # special options for solver
	OPT_SLV    = "''"            # special options for solver
	GRDOPT     = "''"                                                      # special options for grid_module
	MOPT4      = "'-O2'"
#	MOPT4      = "'-O2 -g -finit-real=snan -ffpe-trap=invalid,zero,overflow'"
#	MOPT4      = "'-O0 -g -ffpe-trap=zero,invalid,overflow -fcheck=all'"
#	MOPT4      = "'-O1 -g -fcheck=all'"
#	FPPDEF     = "''"
	MOPT5      = "'-O1'"
	FPPDEF     = "''"
	SOROPT     = "'-O3'"
#	SOROPT     = "'-O1 -g -ffpe-trap=invalid,zero,overflow -fcheck=all'"
	PAR        = "''"
#	AR         = "'sync; libtool -static -o'"
	LDR        = "'mpif90 -fbacktrace'"
	LOPT       = "'-openmp'"
	CC         = "'mpicc'"
	CFLAGS     = "'-c -m64 -O -DLITTLE -DUNDERSCORE -DV5D64'"
# uncomment next lines to compile with netCDF4
	DFLAGS     = "'-DNC4 -DMPI -DV5D64 -DBOXMG -DUSEWRF'"
#	DFLAGS     = "'-DNC4 -DMPI -DV5D64 -DUSEWRF'"
# use "module load netcdf" to set netcdf_libraries
	NETCDF_LIB = "'-L${NETCDF_LIBRARIES} -lnetcdff -lnetcdf -L/Users/ted.mansell/src/boxmg4wrf-git/lib -lboxmg_opt_sgl -lboxmg-extras_opt_sgl'"
	NETCDF_INC = "'-I/Users/Shared/hpcstack-ventura/gnu-11.3.0/openmpi-4.1.2/netcdf/4.7.4/include -I/Users/ted.mansell/src/boxmg4wrf-git/include -I/Users/ted.mansell/src/boxmg4wrf-git/extras/msg/include'"
	LIB        = "''"



if machine == 'x86_64' and system == 'Linux'  and mpi == 'yes':

	F90        = "'mpif90'"
	F77        = "'mpif90'"
	FPP        = "'mpif90'"
	NCARGF     = "'ncargf90'"
	FIXED      = "'-extend_source'"
	FREE       = "''"
	FFLAGS     = "'-O3 -tpp7 -xP -g -CB'"
	FFLAGS     = "'-O2 -ftz -zero'"
#	FFLAGS     = "'-O1'"
#	FFLAGS     = "'-O0 -tpp7 -xP -g -CB'"
	INCS       = "'-I.'"
	LDFLAGS    = FFLAGS
	DFLAGS    = "'-DMPI -DNC4 -DV5D64 -DBOXMG'"
	SMP        = "''"
	IPO        = "''" # "'-ipo'"
	OPT_F90    = FFLAGS
	OPT_F77    = FFLAGS
	OPT_ADV    = "'-O3'"    # FFLAGS
	GRDOPT     = "''"                            # special options for grid_module
	MOPT5      = "'-O1 -zero -save -ftz'"        # use to avoid long compile if 10ICE will not be used
#	MOPT5      = "'-O1 -zero -save -ftz -override_limits'"
	MOPT4      = MOPT5
	FPPDEF     = "''"
	SOROPT     = "'-O0 -ftz -align all'"
	PAR        = "''"
	LDR        = "'mpif90'"
	LOPT       = "'-i_dynamic -openmp'"
	CC         = "'mpicc'"
	CFLAGS     = "'-c -O -DLITTLE -DUNDERSCORE'"
#	NETCDF_LIB = "'-L/usr/lib64/netcdf-3 -lnetcdf'"
#	NETCDF_INC = "'-I/usr/include/netcdf-3'"
#	NETCDF_LIB = "'/home/mansell/local/netcdf4mpi/lib/libnetcdf.a /home/mansell/local/hdf5mpi/lib/libhdf5_hl.a /home/mansell/local/hdf5mpi/lib/libhdf5.a -lz'" # -lSystemStubs'"
#	NETCDF_INC = "'-I/home/mansell/local/netcdf4mpi/include -I/home/mansell/local/hdf5mpi/include'"
#	NETCDF_LIB = "'/home/mansell/local/netcdf4/lib/libnetcdf.a /home/mansell/local/hdf5/lib/libhdf5_hl.a /home/mansell/local/hdf5/lib/libhdf5.a -lz'" # -lSystemStubs'"
#	NETCDF_INC = "'-I/home/mansell/local/netcdf4/include -I/home/mansell/local/hdf5/include'"
	NETCDF_LIB = "'/home/mansell/local/netcdf4openmpi/lib/libnetcdf.a /home/mansell/local/hdf5openmpi/lib/libhdf5_hl.a /home/mansell/local/hdf5openmpi/lib/libhdf5.a -lz /home/mansell/src/boxmg-mpi-single_openmpi/lib/libboxmg_opt_sgl.a /home/mansell/src/boxmg-mpi-single_openmpi/lib/libboxmg-extras_opt_sgl.a'"
	NETCDF_INC = "'-I/home/mansell/local/netcdf4openmpi/include -I/home/mansell/local/hdf5openmpi/include -I/home/mansell/src/boxmg-mpi-single/include -I/home/mansell/src/boxmg-mpi-single/extras/msg/include'"
	LIB        = "''"


#-------------------------------------------------------------------------
#
FCOMPILE       = 'F90=' + F90 + ' F77=' + F77 + ' FPP=' + FPP + ' CC=' + CC + ' FIXED=' + FIXED + ' FREE=' + FREE  \
               + ' OPT_F90=' + OPT_F90 + ' OPT_F77=' + OPT_F77 + ' SMP=' + SMP + ' PAR=' + ' CFLAGS=' + CFLAGS     \
               + ' GRDOPT=' + GRDOPT + ' MOPT4=' + MOPT4 + ' MOPT5=' + MOPT5 + ' OPT_ADV=' + OPT_ADV               \
               + ' SOROPT=' + SOROPT + ' FPPDEF=' + FPPDEF + ' IPO=' + IPO + ' OPT_BUOY=' + OPT_BUOY               \
               + ' OPT_SLV=' + OPT_SLV + ' LDR=' + LDR +  ' LOPT=' + LOPT + ' LIB=' + LIB                          \
               + ' NETCDF_LIB=' + NETCDF_LIB + ' NETCDF_INC=' + NETCDF_INC                                         \
               + ' AR=' + AR + ' RANLIB=' + RANLIB + ' NCARGF=' + NCARGF + ' DFLAGS=' + DFLAGS

#--------------------------------------------------------------------------
# COMPILE DICTIONARY
#                 name           location    target         compile options
#--------------------------------------------------------------------------
#MAKE_DICT      = {'fort_lib':    ['./srcmpi', 'obj',     FCOMPILE], \

MAKE_DICT      = {'commas':      ['./build'+mpisuf, 'commas' ,     FCOMPILE]}
#                  'commas_init': ['./build'+mpisuf, 'commas_init', FCOMPILE], \
#                  'com2v5d':     ['./build'+mpisuf, 'com2v5d',     FCOMPILE], \
#                  'com2nc4':     ['./build'+mpisuf, 'com2nc4',     FCOMPILE]}

MAKE_DICT_PLOT   = {'complot':      ['./build'+mpisuf, 'complot' ,     FCOMPILE]}

MAKE_DICT_TRMM   = {'comtrmm':      ['./build'+mpisuf, 'comtrmm' ,     FCOMPILE]}

MAKE_DICT_HCM   = {'commashcm':      ['./build'+mpisuf, 'commashcm' ,     FCOMPILE]}

MAKE_DICT_TAK   = {'commastak':      ['./build'+mpisuf, 'commastak' ,     FCOMPILE]}

MAKE_DICT_IOTEST   = {'commas_iotest':      ['./build'+mpisuf, 'commas_iotest' ,     FCOMPILE]}

#, \
#                  'filter':      ['./Filter','enkf',        FCOMPILE]}

current_dir = os.getcwd()

if len(sys.argv) == 1:
    print()
    print("No argument! Use 'pymake help' for list of options")
    print()
    print("Assuming 'all' - compiling all!")
    sys.argv.append('all')

if len(sys.argv) > 1:

    print("User argument:  ", sys.argv[1])

    if sys.argv[1] == 'clean':
        print()
        print("Cleaning directory")

        targets = list(MAKE_DICT.keys())

        
        tmp = MAKE_DICT['commas']
        os.chdir(tmp[0])
        os.system(MAKE + " clean")
        os.chdir("..")

        for key in targets:
            tmp = MAKE_DICT[key]
            os.system("rm " + tmp[1] + mpisuf)
#           os.chdir(tmp[0])
#           os.system(MAKE + " clean")
#           os.system("cd " + current_dir)
            print("Cleaned up ", tmp[1])
    
    if sys.argv[1] == 'all':
        targets = list(MAKE_DICT.keys())
        for key in targets:
            tmp = MAKE_DICT[key]
            os.system("rm " + tmp[1] + mpisuf)
            ret = makeit(current_dir,tmp[0],tmp[1],tmp[2],mpisuf)

    if sys.argv[1] == 'complot':
        targets = list(MAKE_DICT_PLOT.keys())
        for key in targets:
            tmp = MAKE_DICT_PLOT[key]
            os.system("rm " + tmp[1] + mpisuf)
            ret = makeit(current_dir,tmp[0],tmp[1],tmp[2],mpisuf)

    if sys.argv[1] == 'comtrmm':
        targets = list(MAKE_DICT_TRMM.keys())
        for key in targets:
            tmp = MAKE_DICT_TRMM[key]
            os.system("rm " + tmp[1] + mpisuf)
            ret = makeit(current_dir,tmp[0],tmp[1],tmp[2],mpisuf)

    if sys.argv[1] == 'commashcm':
        targets = list(MAKE_DICT_HCM.keys())
        for key in targets:
            tmp = MAKE_DICT_HCM[key]
            os.system("rm " + tmp[1] + mpisuf)
            ret = makeit(current_dir,tmp[0],tmp[1],tmp[2],mpisuf)

    if sys.argv[1] == 'commastak':
        targets = list(MAKE_DICT_TAK.keys())
        for key in targets:
            tmp = MAKE_DICT_TAK[key]
            os.system("rm " + tmp[1] + mpisuf)
            ret = makeit(current_dir,tmp[0],tmp[1],tmp[2],mpisuf)

    if sys.argv[1] == 'commas_iotest':
        targets = list(MAKE_DICT_IOTEST.keys())
        for key in targets:
            tmp = MAKE_DICT_IOTEST[key]
            os.system("rm " + tmp[1] + mpisuf)
            ret = makeit(current_dir,tmp[0],tmp[1],tmp[2],mpisuf)

    if sys.argv[1] in MAKE_DICT:
        tmp = MAKE_DICT[sys.argv[1]]
        os.system("rm " + tmp[1] + mpisuf)
        ret = makeit(current_dir,tmp[0],tmp[1],tmp[2],mpisuf)

    if sys.argv[1] == 'help':

        print("==============================================================================================")
        print("                        Python Compile Script for PyEnCOMMAS ") 
        print()
        print("     pymake all  --> To create a running version of PyEnCOMMAS: ") 
        print("                      this creates the commas solver library and python interface routines ") 
        print("                      so one can run the scripts. ")
        print() 
        print("     pymake com2v5d --> To create the COMMAS to Vis5D conversion program") 
        print() 
        print("     pymake clean  --> cleans up the directory, removing object and module files  ") 
        print()
        print("==============================================================================================")
